### ISSUE TITLE
Misses files that vim gets, related to subdirs?

### ISSUE THREAD

**Issue by bronson** [t9md/atom-open-this#2]
I'm editing `tools/readable_bash.py`...   I put my cursor over `setup/start.sh` and type `gf`.  Vim correctly opens `setup/start.sh` but atom-open-this ignores the keypress.

atom-open-this works great when the destination file is in the same directory as the source file.

To reproduce:
- git clone https://github.com/mail-in-a-box/mailinabox
- cd mailinabox
- atom .

Now, open `tools/readable_bash.py`, put the cursor over `setup/start.sh`, and type `gf`.

(I launched vim with `vim -u /dev/null` so I'm pretty sure vim is doing this 100% stock)

**Comment by t9md** [comment]
Currently when PATH under cursor is **relative** file(not start with `/`), open-this tries to open file relative to current file, so trying to find `tools/setup/start.sh` in this case.

The requirement for enhancement is add "try to find file from **current project root**".

I'll try to add feature, wait for a while

**Comment by t9md** [comment]
released as v0.1.9

**Comment by bronson** [comment]
Excellent!  It works great.
