### ISSUE TITLE
resolve to default file in directory (e.g. "./api" to "./api/index.js")

### ISSUE THREAD

**Issue by jpbochi** [t9md/atom-open-this#7]
In my specific use case, I have a line saying `import api from './api';`. There's no `./api.js` file, but there's a `./api/index.js` and that's the one that javascript will import.

Right now, for that case, `open-this` opens a new untitled file. Opening `./api/index.js` would be great.

Maybe, the list of default files to look for when the path resolves to a directory _could_ be configurable. This way, it might end up being useful for other languages, too.

(I have to say I've been using vim-mode-plus for some time now, and I can't live without it. Great work on your plugins.)

**Comment by t9md** [comment]
Imperatively implement your suggestion.

I understand your point, and I don't like my imperative fix above.
But I will postpone for **full-languagge-scope-aware-filepath-detection** until I'm very motivated for that.
Will release once test passed on travisCI.
Thanks for suggestion.

**Comment by jpbochi** [comment]
wow! very fast fix! thanks
