### ISSUE TITLE
open URLs in browser

### ISSUE THREAD

**Issue by jpbochi** [t9md/atom-open-this#8]
When the file path at the cursor is an URL, instead of doing nothing, it could be opened in a browser. To do that, one can simply call `shell.openExternal`, like in https://github.com/zsytssk/open-path/blob/master/lib/open-path.coffee#L28.

If you are interested, I might send a PR implementing that.

**Comment by t9md** [comment]
there is native package `link`.
You can use `link:open` to open it.( I map it `g x` in normal-mode ).
So I'm not interested in to implement it by this package.

**Comment by jpbochi** [comment]
cool. Thanks.
